# -*- coding: utf-8 -*-
import docx2txt

def search_keyword_in_doc(file_path, keyword):
    text = docx2txt.process(file_path)
    if keyword in text:
        return True
    else:
        return False

# 用例
keyword = input()
document_paths = ['C:\\VZW\\4GBPUI.docx',
                'C:\\VZW\\5G SA RAN Features.docx',
                'C:\\VZW\\5Gdevice MgmtAPIsfor5GFCL.docx',
                'C:\\VZW\\5GNR SA E911.docx',
                'C:\\VZW\\5GNR SA LBS.docx',
                'C:\\VZW\\5GNRCoreServiceReqs.docx',
                'C:\\VZW\\5GNRNSAFWA.docx',
                'C:\\VZW\\5GNRNSAMOBILITY.docx',
                'C:\\VZW\\5GNRNSASUPP.docx',
                'C:\\VZW\\5GNRRepeaterReqs.docx',
                'C:\\VZW\\5GNRRouterReqs.docx',
                'C:\\VZW\\5GNRSA.docx',
                'C:\\VZW\\5GNRSAVOICEVIDEO.docx',
                'C:\\VZW\\5GODUBLEONBOARD.docx',
                'C:\\VZW\\5G_FWATBWIFIExt.docx',
                'C:\\VZW\\A002 Release Notes Feb 2023.docx',
                'C:\\VZW\\ACC.docx',
                'C:\\VZW\\ACTIVATIONUI.docx',
                'C:\\VZW\\ADA-ACS_255_716_718_508.docx',
                'C:\\VZW\\ANDROID.docx',
                'C:\\VZW\\AUDIODEV.docx',
                'C:\\VZW\\BT.docx',
                'C:\\VZW\\CARRIERAGG.docx',
                'C:\\VZW\\CERTMGMT.docx',
                'C:\\VZW\\CHR2F_Router_Hardware.docx',
                'C:\\VZW\\CHR_Mini Extender_Hardware.docx',
                'C:\\VZW\\CHR_Sub6_Router_HW_PRD.docx',
                'C:\\VZW\\CMAS.docx',
                'C:\\VZW\\CONFIGUP.docx',
                'C:\\VZW\\DATADEVUI.docx',
                'C:\\VZW\\DATAROAM.docx',
                'C:\\VZW\\DeviceConnectionEfficiency.docx',
                'C:\\VZW\\E911.docx',
                'C:\\VZW\\E911FWT.docx',
                'C:\\VZW\\EAPAKA.docx',
                'C:\\VZW\\ERI.docx',
                'C:\\VZW\\eSE.docx',
                'C:\\VZW\\eUICC.docx',
                'C:\\VZW\\FEMTO.docx',
                'C:\\VZW\\Femtocell Docs.docx',
                'C:\\VZW\\FiOSSC.docx',
                'C:\\VZW\\Flash Reserve Space QLV.docx',
                'C:\\VZW\\HARDWARE.docx',
                'C:\\VZW\\IMS.docx',
                'C:\\VZW\\Integrated SIM Security Comp.docx',
                'C:\\VZW\\IOTDMDO.docx',
                'C:\\VZW\\IOTSEC.docx',
                'C:\\VZW\\LOCDET.docx',
                'C:\\VZW\\LTEAT.docx',
                'C:\\VZW\\LTEB13NAC.docx',
                'C:\\VZW\\LTEDATA.docx',
                'C:\\VZW\\LTEDATARETRY.docx',
                'C:\\VZW\\LTELBSMMDEV.docx',
                'C:\\VZW\\LTELBSNI.docx',
                'C:\\VZW\\LTEMBNAC.docx',
                'C:\\VZW\\LTEMMPST.docx',
                'C:\\VZW\\LTENFCSIM.docx',
                'C:\\VZW\\LTEOTADM.docx',
                'C:\\VZW\\LTEPCO.docx',
                'C:\\VZW\\LTEPOA.docx',
                'C:\\VZW\\LTEPREPAYTAB.docx',
                'C:\\VZW\\LTESIM.docx',
                'C:\\VZW\\LTESMS.docx',
                'C:\\VZW\\LTEVQ.docx',
                'C:\\VZW\\MARKETING.docx',
                'C:\\VZW\\MBHM.docx',
                'C:\\VZW\\MC PTT.docx',
                'C:\\VZW\\MMS.docx',
                'C:\\VZW\\NATAPPUP.docx',
                'C:\\VZW\\NETLOCK.docx',
                'C:\\VZW\\NFC.docx',
                'C:\\VZW\\NGM.docx',
                'C:\\VZW\\OBDM.docx',
                'C:\\VZW\\OneTalkLTEDeskPhone.docx',
                'C:\\VZW\\OTADM-UX.docx',
                'C:\\VZW\\OTADMDIAG-5G CPE.docx',
                'C:\\VZW\\OTADMDIAG.docx',
                'C:\\VZW\\OTADMLWM2M.docx',
                'C:\\VZW\\OTAEUT.docx',
                'C:\\VZW\\PLATMODUP.docx',
                'C:\\VZW\\PLATSEC.docx',
                'C:\\VZW\\PREPAY.docx',
                'C:\\VZW\\PREPAYSMRTPH.docx',
                'C:\\VZW\\PROPNETLOCK.docx',
                'C:\\VZW\\PROPOTA.docx',
                'C:\\VZW\\PROPOTACONN.docx',
                'C:\\VZW\\PSTR.docx',
                'C:\\VZW\\PushToTalk.docx',
                'C:\\VZW\\PWRMGT.docx',
                'C:\\VZW\\RCS.docx',
                'C:\\VZW\\RCSCHAT.docx',
                'C:\\VZW\\RCSVOLTE.docx',
                'C:\\VZW\\Reqs - Stream TV RC.docx',
                'C:\\VZW\\Reqs - Stream TV.docx',
                'C:\\VZW\\Reqs-COBRA 2.docx',
                'C:\\VZW\\Reqs-COBRA.docx',
                'C:\\VZW\\Reqs-SOUNDBAR.docx',
                'C:\\VZW\\Reqs-TR-069.docx',
                'C:\\VZW\\REQ_MoCA_Adapter_PRD_SKU1.docx',
                'C:\\VZW\\REQ_MoCA_Adapter_PRD_SKU2.docx',
                'C:\\VZW\\RRLT.docx',
                'C:\\VZW\\RTT-UX.docx',
                'C:\\VZW\\SERNUM.docx',
                'C:\\VZW\\SETWIZ.docx',
                'C:\\VZW\\SETWIZTABUI.docx',
                'C:\\VZW\\SETWIZUI.docx',
                'C:\\VZW\\SHIPDEL.docx',
                'C:\\VZW\\SingleSKU.docx',
                'C:\\VZW\\SMARTHOME.docx',
                'C:\\VZW\\SMARTPHONE.docx',
                'C:\\VZW\\SOFTRESETMODE.docx',
                'C:\\VZW\\Stream TV Delta UI Screens.docx',
                'C:\\VZW\\StreamTV _Product_Reqs.docx',
                'C:\\VZW\\SUA.docx',
                'C:\\VZW\\SUACONN.docx',
                'C:\\VZW\\SUSTAINABILITY.docx',
                'C:\\VZW\\UI.docx',
                'C:\\VZW\\UICCAPP.docx',
                'C:\\VZW\\UICCSIM.docx',
                'C:\\VZW\\UNIDESIGN.docx',
                'C:\\VZW\\Verizon Application Download.docx',
                'C:\\VZW\\VISIBLE.docx',
                'C:\\VZW\\VOLTEDEVICEUI.docx',
                'C:\\VZW\\VOLTEPERF.docx',
                'C:\\VZW\\VOWIFI.docx',
                'C:\\VZW\\VVM.docx',
                'C:\\VZW\\VZOTADM.docx',
                'C:\\VZW\\VZWCLOUD.docx',
                'C:\\VZW\\WAP2.docx',
                'C:\\VZW\\WFMH.docx',
                'C:\\VZW\\Wi-Fi Auto Connect Extender.docx',
                'C:\\VZW\\Wi-Fi_Perf_Reqs.docx',
                'C:\\VZW\\WIFI.docx',
                'C:\\VZW\\WIFIMH.docx',
                'C:\\VZW\\WIFIMHSUI.docx',
                'C:\\VZW\\WiFiPERFMHS.docx',
                'C:\\VZW\\WIFISSIDPASS.docx',
                'C:\\VZW\\WIFIUI.docx'
                                    ] # 修改为您自己的文档路径列表

for file_path in document_paths:
    if search_keyword_in_doc(file_path, keyword):
        print(f"在 {file_path} 中找到了关键词")
    else:
        pass